# Generated by Django 4.0.4 on 2023-05-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del sorteo', max_length=200, unique=True, verbose_name='nombre')),
                ('details', models.TextField(help_text='Detalles del sorteo', verbose_name='detalles')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Precio total del sorteo (el costo de los boletos será: precio total / cantidad de boletos)', max_digits=10, verbose_name='precio total')),
                ('image', models.URLField(help_text='URL de la imagen del sorteo', verbose_name='imagen')),
                ('end_date', models.DateTimeField(help_text='Fecha de finalización del sorteo', verbose_name='fecha de finalización')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del sorteo', verbose_name='fecha de creación')),
                ('numbers', models.IntegerField(help_text='Cantidad de números que se pueden elegir en el sorteo', verbose_name='cantidad de números')),
                ('is_open', models.BooleanField(default=True, help_text='Indica si el sorteo está abierto', verbose_name='abierto')),
            ],
            options={
                'verbose_name': 'sorteo',
                'verbose_name_plural': 'sorteos',
            },
        ),
    ]
