# Generated by Django 4.0.4 on 2023-05-18 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(help_text='Número del boleto', verbose_name='número')),
                ('buyer_name', models.CharField(help_text='Nombre del comprador del boleto', max_length=200, verbose_name='dueño')),
                ('buyer_email', models.EmailField(help_text='Correo electrónico del comprador del boleto', max_length=254, verbose_name='correo electrónico')),
                ('buy_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de apartado del boleto', verbose_name='fecha de apartado')),
                ('is_paid', models.BooleanField(default=False, help_text='Indica si el boleto ha sido pagado', verbose_name='pagado')),
                ('active', models.BooleanField(default=True, help_text='Indica si el boleto está activo', verbose_name='activo')),
                ('lottery', models.ForeignKey(help_text='Sorteo al que pertenece el boleto', on_delete=django.db.models.deletion.CASCADE, to='lottery.lottery', verbose_name='sorteo')),
            ],
            options={
                'verbose_name': 'boleto',
                'verbose_name_plural': 'boletos',
                'unique_together': {('lottery', 'number')},
            },
        ),
    ]
