# Generated by Django 4.0.4 on 2023-05-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='details',
            field=models.TextField(blank=True, help_text='Detalles del sorteo', null=True, verbose_name='detalles'),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Fecha de finalización del sorteo', null=True, verbose_name='fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='lottery',
            name='image',
            field=models.URLField(blank=True, help_text='URL de la imagen del sorteo', null=True, verbose_name='imagen'),
        ),
    ]
