# Generated by Django 4.0.4 on 2023-05-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_alter_lottery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='image',
            field=models.BinaryField(blank=True, help_text='Imagen del sorteo', null=True, verbose_name='imagen'),
        ),
    ]
