# Generated by Django 4.0.4 on 2023-05-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0005_alter_lottery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del sorteo', null=True, upload_to='lottery', verbose_name='imagen'),
        ),
    ]
