# Generated by Django 4.0.4 on 2023-05-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0006_alter_lottery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='end_date',
            field=models.DateField(help_text='Fecha de cierre del sorteo', verbose_name='fecha de cierre'),
        ),
    ]
