# Generated by Django 4.0.4 on 2023-05-20 00:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0009_alter_lottery_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='buy_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de apartado del boleto', verbose_name='fecha de apartado'),
        ),
    ]
