# Generated by Django 4.0.4 on 2023-05-20 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0010_alter_ticket_buy_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
    ]
