# Generated by Django 4.0.4 on 2023-05-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0011_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='buyer_email',
        ),
        migrations.AddField(
            model_name='ticket',
            name='buyer_phone',
            field=models.IntegerField(blank=True, help_text='Teléfono del comprador del boleto', null=True, verbose_name='teléfono'),
        ),
    ]
